# Generated by Django 3.2.5 on 2024-09-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coursemodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100, null=True)),
                ('year', models.CharField(max_length=100, null=True)),
                ('fees', models.IntegerField(null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notifiction_Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registerno', models.CharField(max_length=100, unique=True)),
                ('course', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(max_length=500, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notifiction_Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registerno', models.CharField(max_length=100, unique=True)),
                ('course', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(max_length=500, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staffmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_registerid', models.CharField(max_length=100, unique=True)),
                ('staff_name', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(max_length=100, null=True)),
                ('age', models.CharField(max_length=100, null=True)),
                ('qualification', models.CharField(max_length=100, null=True)),
                ('phone', models.IntegerField(default=False, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studentmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registerno', models.CharField(max_length=100, null=True, unique=True)),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('course', models.CharField(max_length=100, null=True)),
                ('year', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=100, null=True)),
                ('staff', models.CharField(max_length=100, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
