# Generated by Django 3.2.5 on 2024-09-19 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_auto_20240918_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmodel',
            name='subject',
        ),
    ]
