# Generated by Django 3.2.5 on 2024-09-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0004_remove_staffmodel_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifiction_staff',
            name='registerno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notifiction_student',
            name='registerno',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
