# Generated by Django 3.2.5 on 2024-09-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0005_auto_20240919_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifiction_staff',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notifiction_student',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
