# Generated by Django 3.2.5 on 2024-10-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0006_auto_20240919_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelname', models.CharField(max_length=100)),
                ('savedid', models.CharField(max_length=100)),
                ('operationdone', models.CharField(max_length=100)),
                ('donebyuser', models.CharField(max_length=100)),
                ('donebyuserrole', models.CharField(max_length=100)),
                ('donedatetime', models.DateTimeField(max_length=100)),
                ('description', models.CharField(default='True', max_length=300)),
                ('donebyemployeeid', models.CharField(max_length=100, null=True)),
                ('historyflag', models.BooleanField(default=False)),
            ],
        ),
    ]
