# Generated by Django 3.2.5 on 2024-08-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signinmodel',
            name='userrole',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
