# Generated by Django 3.2.5 on 2024-09-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loginapp', '0002_signinmodel_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='signinmodel',
            name='staff_id',
            field=models.CharField(default='false', max_length=100, unique=True),
        ),
    ]
