# Generated by Django 3.2.5 on 2024-09-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loginapp', '0003_signinmodel_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signinmodel',
            name='userrole',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
