# Generated by Django 3.2.5 on 2024-09-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loginapp', '0004_alter_signinmodel_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signinmodel',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='signinmodel',
            name='userrole',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
