# Generated by Django 3.2.5 on 2024-09-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('attendance', models.JSONField(default={'Attendance': 'Present', 'Name': 'null'})),
            ],
        ),
    ]
