# Generated by Django 3.2.5 on 2024-09-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0002_attendance_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
