# Generated by Django 3.2.5 on 2024-09-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0004_auto_20240912_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='regno',
            field=models.CharField(default=False, max_length=100, unique=True),
        ),
    ]
