# Generated by Django 3.2.5 on 2024-09-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0007_auto_20240912_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regno', models.CharField(default=False, max_length=100)),
                ('course', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
