# Generated by Django 3.2.5 on 2024-09-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0010_applystaffleave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applystaffleave',
            old_name='grade',
            new_name='status',
        ),
    ]
