# Generated by Django 3.2.5 on 2024-09-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0011_rename_grade_applystaffleave_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_Student_Leave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regno', models.CharField(max_length=100, null=True)),
                ('course', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('date_on', models.DateField(null=True)),
                ('date_to', models.DateField(null=True)),
                ('message', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
