# Generated by Django 3.2.5 on 2024-09-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0012_apply_student_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresult',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
